language: node_js

install:
  - npm install
  - npm install coveralls

script:
  - npm run lint
  - npm run tsc
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

node_js:
  - 'stable'
  - 'lts/*'
